### ISSUE TITLE
How can I get "tag_dump.pkl" file?

### ISSUE THREAD

**Issue by SSUHan** [blandocs/Tag2Pix#1]
Hi

I want to execute the code with train phase, but I cannot find "tag_dump.pkl" file.
how can I get this file ?

Thanks!

<img width="625" alt="스크린샷 2019-09-02 오후 12 34 21" src="https://user-images.githubusercontent.com/8327479/64088341-eea56900-cd7b-11e9-95bd-efe94a7026f0.png">

**Comment by MerHS** [comment]
We have uploaded that file. ([loader/tag_dump.pkl](https://github.com/blandocs/Tag2Pix/tree/master/loader)).

Please try again `git pull`.
