### ISSUE TITLE
scipy.misc.imsave is removed in SciPy 1.2.0

### ISSUE THREAD

**Issue by azuse** [blandocs/Tag2Pix#2]
Hi,

from [SciPy document](https://docs.scipy.org/doc/scipy-1.1.0/reference/generated/scipy.misc.imsave.html): 
> imsave is deprecated! imsave is deprecated in SciPy 1.0.0, and will be removed in 1.2.0. Use imageio.imwrite instead. 

`scipy.misc.imsave` is used in `utils.py`. 

Maybe consider switch it to `imageio.imwrite` or add comment that SciPy under ver 1.2.0 should be installed.

Thanks

**Comment by blandocs** [comment]
Hi, thank you for sharing!

We added a comment that SciPy under ver 1.2.0 should be installed.

Thanks :)

**Comment by MerHS** [comment]
Switched it to `imageio`. :)
