### ISSUE TITLE
Which version of keras and tensorflow did you use?

### ISSUE THREAD

**Issue by UdonDa** [blandocs/Tag2Pix#3]
Thanks for sharing the nice code.
I do not know which version of keras and tensorflow you used.
Please teach us.
Thank you.

**Comment by MerHS** [comment]
We used Tensorflow and Keras only for making training datasets. Especially [sketchKeras](https://github.com/lllyasviel/sketchKeras)

It is sufficient to run sketchKeras with tensorflow.
